version: '3'

services:

  limesurvey:
    build: .
    image: crramirez/limesurvey:3.14.11
    ports:
      - 80:80
    volumes:
    - plugins:/var/www/html/plugins
    - upload:/var/www/html/upload

    environment:
      LIMESURVEY_DB_PASSWORD: example
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  plugins:
  upload:
